import { NextResponse } from 'next/server';

export async function GET() {
  return NextResponse.json({
    repos: [
      {
        name: 'malicious-url-detector',
        description: 'A tool to detect malicious URLs using pattern recognition and security analysis techniques.',
        url: 'https://github.com/jesowin/malicious-url-detector',
        homepage: null,
        stars: 0,
        forks: 0,
        isArchived: false,
        updatedAt: new Date().toISOString(),
        openIssues: 0,
        totalCommits: 50,
        commitActivity: [],
        languages: [{ name: 'Python', color: '#3572A5', percentage: 100 }],
        topics: ['security', 'python', 'url-analysis'],
        ownerAvatar: 'https://avatars.githubusercontent.com/u/jesowin',
      },
      {
        name: 'PhishShield',
        description: 'A phishing detection system designed to identify suspicious links and protect users.',
        url: 'https://github.com/jesowin/PhishShield',
        homepage: null,
        stars: 0,
        forks: 0,
        isArchived: false,
        updatedAt: new Date().toISOString(),
        openIssues: 0,
        totalCommits: 45,
        commitActivity: [],
        languages: [{ name: 'Python', color: '#3572A5', percentage: 100 }],
        topics: ['phishing', 'security', 'python'],
        ownerAvatar: 'https://avatars.githubusercontent.com/u/jesowin',
      },
      {
        name: 'Network',
        description: 'Networking-related implementations and experiments covering core networking concepts.',
        url: 'https://github.com/jesowin/Network',
        homepage: null,
        stars: 0,
        forks: 0,
        isArchived: false,
        updatedAt: new Date().toISOString(),
        openIssues: 0,
        totalCommits: 30,
        commitActivity: [],
        languages: [{ name: 'Python', color: '#3572A5', percentage: 100 }],
        topics: ['networking'],
        ownerAvatar: 'https://avatars.githubusercontent.com/u/jesowin',
      },
      {
        name: 'Drive-uploads',
        description: 'A system for handling and managing file uploads efficiently.',
        url: 'https://github.com/jesowin/Drive-uploads',
        homepage: null,
        stars: 0,
        forks: 0,
        isArchived: false,
        updatedAt: new Date().toISOString(),
        openIssues: 0,
        totalCommits: 20,
        commitActivity: [],
        languages: [{ name: 'JavaScript', color: '#f1e05a', percentage: 100 }],
        topics: ['upload', 'drive'],
        ownerAvatar: 'https://avatars.githubusercontent.com/u/jesowin',
      },
    ],
  });
}
